# Generated by Django 3.1.1 on 2020-11-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
    ]
